<!-- swiper-slide start -->
                                <div class="new-arrival-carousel-item swiper-slide">
                                    <!-- product-card-list start -->
                                    <div class="product-card-list">
                                        <!-- product-card start -->
                                        <div class="product-card">
                                            <span class="badge bg-success product-badge">new</span>
                                            <div class="product-thumb-nail">
                                                <a href='[field:arcurl /]' title="[field:title function='htmlspecialchars(@me)'/] "><img src='[field:litpic/]' alt="[field:title function='htmlspecialchars(@me)'/] "></a>
                                                <!-- <ul class="actions">
                                                    <li class="action quick-view">
                                                        <button data-bs-toggle="modal"
                                                            data-bs-target="#product-modal"><i
                                                                class="las la-eye"></i></button>
                                                    </li>
                                                </ul> -->
                                            </div>
                                            <div class="product-content">
                                                <h3 class="product-title fw-normal text-center">[field:textlink/]</h3>
                                            </div>
                                        </div>
                                        <!-- product-card end -->
                                    </div>
 
                                    <!-- product-card-list end -->
                                    
                                </div>
                                <!-- swiper-slide end-->