
    <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='关于我们' ischannel='1' link='content_list.php?channelid=16' linkadd='archives_add.php?channelid=16' channelid='16' rank='' target='main' />
  <m:item name='客户案例' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='帮助中心' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='尺码与版型' ischannel='1' link='content_list.php?channelid=19' linkadd='archives_add.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='印花/绣花技术' ischannel='1' link='content_list.php?channelid=20' linkadd='archives_add.php?channelid=20' channelid='20' rank='' target='main' />
  <m:item name='产品与服务' ischannel='1' link='content_list.php?channelid=21' linkadd='archives_add.php?channelid=21' channelid='21' rank='' target='main' />

  <m:item name='专题管理' ischannel='1' link='content_s_list.php' linkadd='spec_add.php' channelid='-1' rank='spec_New' target='main' />
