<?php
$z[0]=Array("array","\r\n                      @me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me[' arcurl']}'><img\r\n                          class='product-image rounded-top rounded-5' src='{@me[' litpic']}' alt='{@me['\r\n                          title']}' /></a>\");\r\n                      ",311,619);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",1137,1152);
$z[1][4]=array();
$z[2]=Array("title","",1154,1168);
$z[2][4]=array();

?>