<ul class="sm_results" style="display: block;">
					{dede:type}
					<li class="sm_header"><a href="[field:typeurl/]">[field:typename /]</a></li>
					{/dede:type}
					{dede:channel type='son'}
					<li class="sm_disabled"><a href="[field:typeurl/]">[field:typename /]</a></li>
					{/dede:channel}
					<li class="sm_divider"></li>
					<li class="sm_header"><a href="javascript:void(0);">Technology Site</a></li>
									<li><a href="https://github.com"><i class="fa fa-fw fa-github"></i> GitHub</a></li>
									<li><a href="https://www.reddit.com"><i class="fa fa-fw fa-reddit"></i> Reddit</a></li>
									<li class="sm_disabled"><a href="javascript:void(0);"><i class="fa fa-fw fa-facebook"></i> Facebook</a></li>
									<li class="sm_disabled"><a href="javascript:void(0);"><i class="fa fa-fw fa-twitter"></i> Twitter</a></li>
									<li class="sm_divider"></li>
									<li class="sm_header"><a href="javascript:void(0);">Actions</a></li>
									<li><a href="javascript:void(0);">Click this menu item to trigger your callback</a></li>
				</ul>