<?php
$z[0]=Array("channel","\n					<li class=\"list-group-item py-3 px-4\">\n						<a class=\"link-hover\" href='[field:typelink/]'>[field:typename/]</a>\n					</li>\n					",267,568);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['currentstyle']="<li class='list-group-item py-3 px-4 bg-light'><a class='text-success' href='~typelink~'>~typename~</a> </li>";
$z[1]=Array("arclist","\n					<div class=\"col-12\">\n						<a class=\"w-25\" href=\"[field:arcurl/]\" class=\"post-thumb\">\n							[field:title function='html2text(@me)'/]\n						</a>\n					</div>\n					",845,1076);
$z[1][4]=array();
$z[1][4]['row']="8";
$z[1][4]['orderby']="click";
$z[1][4]['type']="image.";
$z[2]=Array("tag"," <a class=\"widget-tag-link\" href='[field:link/]'>[field:tag\n					/]</a>\n				",1301,1429);
$z[2][4]=array();
$z[2][4]['row']="15";
$z[2][4]['sort']="new";
$z[2][4]['getall']="0";

?>