<?php
$z[0]=Array("channel","\n            <li class=\"footer-menu-items\"><a class=\"footer-menu-link\" href='[field:typeurl/]'>[field:typename/]</a></li>\n            ",1148,1460);
$z[0][4]=array();
$z[0][4]['typeid']="3";
$z[0][4]['currentstyle']="<li class=";
$z[0][4]['footer-menu-items"><a class']="footer-menu-link";
$z[0][4]['href']="~typelink~";
$z[0][4]['>~typename~</a> </li> "']="";
$z[1]=Array("channel","\n            <li class=\"footer-menu-items\"><a class=\"footer-menu-link\" href='[field:typeurl/]'>[field:typename/]</a></li>\n            ",1732,2044);
$z[1][4]=array();
$z[1][4]['typeid']="4";
$z[1][4]['currentstyle']="<li class=";
$z[1][4]['footer-menu-items"><a class']="footer-menu-link";
$z[1][4]['href']="~typelink~";
$z[1][4]['>~typename~</a> </li> "']="";

?>